//
//  GitHubUserListsInteractor.swift
//  GitUsers
//
//  Created by Teravat Nepiyachat on 5/4/2564 BE.
//  Copyright (c) 2564 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IGitHubUserListsInteractor {
	func getUsers(request: GetGitHubUsers.Request)
}

struct GitHubUserListsInteractor {
	
	let presenter: IGitHubUserListsPresenter
	let worker: IGitHubUserListsWorker
	
	init(presenter: IGitHubUserListsPresenter, worker: IGitHubUserListsWorker) {
		self.presenter = presenter
		self.worker = worker
	}
	
}

// MARK: - IGitHubUserListsInteractor

extension GitHubUserListsInteractor: IGitHubUserListsInteractor {
	func getUsers(request: GetGitHubUsers.Request) {
		
	}
}
