//
//  GitHubUserListsRouter.swift
//  GitUsers
//
//  Created by Teravat Nepiyachat on 5/4/2564 BE.
//  Copyright (c) 2564 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IGitHubUserListsRouter {
	func goToDetail(from viewController: UIViewController, gitUserModel: IGitHubUserListsModel)
}

struct GitHubUserListsRouter { }

// MARK: - IGitHubUserListsRouter

extension GitHubUserListsRouter: IGitHubUserListsRouter {
	func goToDetail(from viewController: UIViewController, gitUserModel: IGitHubUserListsModel) {
		if let gitHubUserDetailViewController = GitHubUserDetailViewController.newInstance(parameters: ["userModel": gitUserModel]) as? GitHubUserDetailViewController {
			viewController.navigationController?.pushViewController(gitHubUserDetailViewController, animated: true)
		}
	}
}
