//
//  GitHubUserDetailViewController.swift
//  GitUsers
//
//  Created by Teravat Nepiyachat on 7/4/2564 BE.
//  Copyright (c) 2564 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GitHubUserDetailDisplayLogic: class {
	
}

class GitHubUserDetailViewController: UIViewController {
	
	// MARK: - Assembly
	var interactor: IGitHubUserDetailInteractor!
	var router: IGitHubUserDetailRouter!
	
	// MARK: - IBOutlets
	
	// MARK: - Lifecycle
	deinit {
		print("deinit \("GitHubUserDetail")ViewController")
	}
	
	class func newInstance(parameters: [String: Any]?) -> UIViewController {
		let storyboard = UIStoryboard(name: "GitHubUserDetail", bundle: nil)
		if let viewController = storyboard.instantiateViewController(withIdentifier: "GitHubUserDetailViewController") as? GitHubUserDetailViewController {
			viewController.setup(parameters: parameters)
			return viewController
		}
		return UIViewController()
	}
	
	override func viewDidLoad() {
		super.viewDidLoad()
		title = "GitHubUserDetail"
		setupUI()
		setNeedsStatusBarAppearanceUpdate()
	}
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
		
	}
	
	override var preferredStatusBarStyle: UIStatusBarStyle {
		return .default
	}
	
}

// MARK: - Private

private extension GitHubUserDetailViewController {
	
	func setup(parameters: [String: Any]?) {
		let viewController = self
		let presenter = GitHubUserDetailPresenter(viewController: viewController)
		let worker = GitHubUserDetailWorker()
		let interactor = GitHubUserDetailInteractor(presenter: presenter, worker: worker)
		let router = GitHubUserDetailRouter()
		viewController.interactor = interactor
		viewController.router = router
	}
	
	func setupUI() {
		
	}
	
}

// MARK: - GitHubUserDetailDisplayLogic

extension GitHubUserDetailViewController: GitHubUserDetailDisplayLogic {
	
}
